config/routes.rb
Plastix2::Application.routes.draw do
  resources :products

  resources :categories

  resources :homes
	match '/homes/search/:id', :controller =>'homes', :action => 'search'
	match '/homes/search2/:id', :controller =>'homes', :action => 'search2'
	match '/homes/search3/:id', :controller =>'homes', :action => 'search3'
	match '/homes/search4/:id', :controller =>'homes', :action => 'search4'
	match '/homes/choose/:id', :controller =>'homes', :action => 'choosecat'
	match '/homes/choose2/:id', :controller =>'homes', :action => 'choosecat2'
	match '/homes/choose3/:id', :controller =>'homes', :action => 'choosecat3'
	match '/homes/choose4/:id', :controller =>'homes', :action => 'chooseprod'
	match '/homes/copy/:id', :controller =>'homes', :action => 'copy'
	match '/homes/variation/:id', :controller =>'homes', :action => 'variation'
	match '/homes/catnew/:id', :controller =>'homes', :action => 'catnew'
	match '/homes/prodnew/:id', :controller =>'homes', :action => 'prodnew'
	
	
	

end

app/models/home.rb
class Home < ActiveRecord::Base

def self.search(search_item)
       if search_item
        self.where('section LIKE ?', "%#{search_item}%")    #Handles the ajax call.
       else
        self.all                                            #Handles the html call on startup.
       end
    end
    
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.xml
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.xml
  def show
    @home = Home.find(params[:id])
    if !params[:productid].nil? 
    @product2 = Product.find(params[:productid])
    puts 'This is the @product2'
    puts @product2.name
    if !@product2.category_id.nil?
    @parentcat = Category.find(@product2.category_id)
    
    if !@parentcat.parentid.nil?
    @parentcat2 = Category.find(@parentcat.parentid)
    if !@parentcat2.parentid.nil?
    @parentcat3 = Category.find(@parentcat2.parentid)
    end
    end
    end
    
    end
    @testid = params[:categoryid]
    if !@testid.nil?
    @testcat = Category.find(@testid)
    puts 'testing'
    @category2=Category.find(params[:categoryid])
    if !@category2.parentid.nil?
    	@parenttest = Category.find(@category2.parentid)
    	if !@parenttest.parentid.nil?
    		@parentcat = @category2
    		@parentcat2 = @parenttest
    		@parentcat3 = Category.find(@parenttest.parentid)
    	else
    		@parentcat2 = @category2
    		@parentcat3 = @parenttest
    	end
    else 
    	@parentcat3 = @category2
    end
    
    
    end
    #@phrase = Category.search(params[:category]) #".search method is in the Model"
    
	@categories = Category.all
	#@categories = Category.find(:all) #, :conditions => ['parentid=?', nil]) 
	
	@categoryinit = []
	@categories.each do |category|
	if category.parentid.nil?
	@categoryinit << category
	
	end
	end
	
	
    @category = Category.new
    @products = Product.all
    @product = Product.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.xml
  def new
  @test=Category.find(params[:id])
 
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.xml
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to(@home, :notice => 'Home was successfully created.') }
        format.xml  { render :xml => @home, :status => :created, :location => @home }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.xml
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to(@home, :notice => 'Home was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

# Search
def search

	@test=params[:parent]
 	puts 'test search 1'
	@categories = Category.all
	@category = Category.new
	#@products = Product.all
    @product = Product.new

if !params[:id].nil?
    @phrase = params[:id] 
    #@category2 = Category.find(params[:id])
    puts '@category2'
    puts @category2
    
    @categoryname = Category.find(@phrase)
    @category2 = @categoryname
    @products2 =Product.find(:all, :conditions => ['category_id=?', @categoryname.id])   

	@products = []
	@products2.each do |products2|
	puts products2.name
	puts products2.parentid
	if products2.parentid.nil?
	@products << products2
	
	end
	end

#prototype solution will not work with jquery
#render :update do |page| 
 # page.replace_html 'results', :partial => 'searchresults'
      #Also update the preview
  #page.replace_html 'preview', :partial => 'category'
#end




    #render :partial => 'chosencat'
    render :partial => 'searchresults'
    #render :partial => 'category'

  end
  
     
end       

def search2

@test=params[:parent]
  
	@product = Product.new
if !params[:id].nil?
    @phrase2 = params[:id] 
    @productname = Product.find(@phrase2)
    
    
    
    if !@productname.category_id.nil?
    @parentcat = Category.find(@productname.category_id)
    
    if !@parentcat.parentid.nil?
    @parentcat2 = Category.find(@parentcat.parentid)
    if !@parentcat2.parentid.nil?
    @parentcat3 = Category.find(@parentcat2.parentid)
    end
    end
    end
    
    
    
    @prodvar= Product.find(:all, :conditions => ['parentid=?', @productname.id])
    
    
    
    
    render :partial => 'searchresults2'

  end
          
end       

def search3

	#@products = Product.all
    @product = Product.new
	@category = Category.new
	@categories = Category.all
if !params[:id].nil?
    @phrase3 = params[:id] 
    @categoryname2 = Category.find(@phrase3)
    @products2 =Product.find(:all, :conditions => ['category_id=?', @categoryname2.id])   
	@parentcat = Category.find(@categoryname2.parentid)
    
    
    @products = []
	@products2.each do |products2|
	puts products2.name
	puts products2.parentid
	if products2.parentid.nil?
	@products << products2
	
	end
	end
    
    
    render :partial => 'searchresults3'

  end
          
end       

def search4

	@products = Product.all
    @product = Product.new
	@categories = Category.all
if !params[:id].nil?
    @phrase4 = params[:id] 
    @categoryname3 = Category.find(@phrase4)
    @parentcat = Category.find(@categoryname3.parentid)
    @parentcat2 = Category.find(@parentcat.parentid)
    @products2 =Product.find(:all, :conditions => ['category_id=?', @categoryname3.id])
    
    
    @products = []
	@products2.each do |products2|
	puts products2.name
	puts products2.parentid
	if products2.parentid.nil?
	@products << products2
	
	end
	end
    
    
    render :partial => 'searchresults4'

  end
          
end       


def choosecat
	@category2 = Category.find(params[:id])
	if !@category2.parentid.nil?
	@parentcat = Category.find(@category2.parentid)
	
	if !@parentcat.parentid.nil?
   	@parentcat2 = Category.find(@parentcat.parentid)
    if !@parentcat2.parentid.nil?
    @parentcat3 = Category.find(@parentcat2.parentid)
	end
	end
	end
	puts '@parentcat2'
	puts @parentcat2
	puts '@category2'
	puts @category2
	@category = Category.new
	render :partial => 'category'

end

def choosecat2
	@category2 = Category.find(params[:id])
	@parentcat = @category2
	if !@parentcat.parentid.nil?
	
	@parentcat2 = Category.find(@parentcat.parentid)
	end
	
	
	puts '@parentcat2'
	puts @parentcat2.name
	puts '@category2'
	puts @category2.name
	@category = Category.new
	render :partial => 'category'

end

def choosecat3
	@parentcat = Category.find(params[:id])
	@parentcat2 = Category.find(@parentcat.parentid)
	@parentcat3 = Category.find(@parentcat2.parentid)
	@category2 = @parentcat
	render :partial => 'category'
end

def chooseprod
	@product2 = Product.find(params[:id])
	if !@product2.category_id.nil?
    @parentcat = Category.find(@product2.category_id)
    
    if !@parentcat.parentid.nil?
    @parentcat2 = Category.find(@parentcat.parentid)
    if !@parentcat2.parentid.nil?
    @parentcat3 = Category.find(@parentcat2.parentid)
    end
    end
    end
    @products = Product.all
    @product = Product.new
	render :partial => 'product'
end
def variation

	@phrase2 = params[:id] 
    @productname = Product.find(@phrase2)
	@parent2= Product.find(params[:id])
	@product = Product.new
	render :partial => '/products/form.html'
end

def copy
	
	if !params[:id].nil?
    @phrase2 = params[:id] 
    @productname = Product.find(@phrase2)
	end
	
	@products = Product.all
    @product = Product.new
	@categories = Category.all
	
	render :partial => '/products/copy.html'

end

def catnew
	@category = Category.new
	@testid = params[:id]
    if !@testid.nil?
    @testcat = Category.find(@testid)
    puts 'testing'
    
    @category2=Category.find(params[:id])
    if !@category2.parentid.nil?
    	@parenttest = Category.find(@category2.parentid)
    	if !@parenttest.parentid.nil?
    		@parentcat = @category2
    		@parentcat2 = @parenttest
    		@parentcat3 = Category.find(@parenttest.parentid)
    	else
    		@parentcat2 = @category2
    		@parentcat3 = @parenttest
    	end
    else 
    	@parentcat3 = @category2
    end
    
    
    end
render :partial => '/categories/form.html'

end

def prodnew
	@product = Product.new
	
	render :partial => '/products/form.html'

end




  # DELETE /homes/1
  # DELETE /homes/1.xml
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to(homes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_category.html.erb
<% if !@category2.nil? %>
<div class="leftcolumn3">
<%= image_tag ("/images/mani_loaded.jpg") %><br />
<%= link_to "View Quote Form", "/quoteform.pdf" %><br />
</div>
<div class="rightcolumn4">
<div id="choose1">
<% if !@category2.nil? %>
<b>Main Category: </b>
<% if !@parentcat3.nil? %>
	<%= @parentcat3.name %><br />
	<%= @parentcat3.description %><br />
<% elsif !@parentcat2.nil? %>
	<%= @parentcat2.name %><br />
	<%= @parentcat2.description %><br />
<% elsif %>
	<% if !@parentcat.nil? %>
		<%= @parentcat.name %><br />
		<%= @parentcat.description %><br />
	<% end %>
<% else %>
	<%= @category2.name %>
<% end %>	
<% end %>
</div>
<div id="choose2">


	<% if !@parentcat3.nil? %>
			<% if !@parentcat2.nil? %>
			<b>Sub Category: </b>
			
			<%= @parentcat2.name %><br />
			<%= @parentcat2.description %><br />
			<% end %>
	<% elsif !@parentcat2.nil? %>
	<% if !@parentcat.nil? %>
	<b>Sub Category: </b>
			<%= @parentcat.name %><br />
			<%= @parentcat.description %><br />
	<% end %>		
	<% end %>







	<% if !@parentcat3.nil? %>
			<% if !@parentcat.nil? %>
			<b>Sub sub Category:</b>
			
			<%= @parentcat.name %><br />
			<%= @parentcat.description %><br />
			<% end %>
	<% end %>
	
</div>
</div>
<div class="list">
<% if !@category2.nil? %>
<p>
<%= link_to "Upload an image for this category", "#" %> | 
<%= link_to "Upload a document for this category", "#" %> 
</p>  
<% end %>
  
<% if !@testid.nil? %>
<div>
<% if !@parentcat3.nil?  && @parentcat2.nil? %>
	
<%= link_to "Create a New Sub Category", '#', :class => 'addWidget2', :"data-parent-id" => @category2.id, :remote => true %>

<script>
	jQuery(function($) {
	$('.addWidget2').click(function(){
	//($(this).attr('data-parent-id'));
	//$( "#preview" ).html( "<%= escape_javascript( render( :partial => "categories/form.html" )) %>" );
	
	var country = ($(this).attr('data-parent-id'));
    if(country == "") country="0";
     
   $.get('/homes/catnew/' +  country, function(data){	
       $("#preview").html(data);
        });

});
});
</script>
|
<% end %>


<% if !@parentcat2.nil?  && @parentcat.nil? %>
<%= link_to "Create a New Sub Sub Category", '#', :class => 'addWidget3', :"data-parent-id" => @category2.id, :remote => true %>

<script>
	jQuery(function($) {
	$('.addWidget3').click(function(){
	//($(this).attr('data-parent-id'));
	//$( "#preview" ).html( "<%= escape_javascript( render( :partial => "categories/form.html" ) ) %>" );
	var country = ($(this).attr('data-parent-id'));
    if(country == "") country="0";
     
   $.get('/homes/catnew/' +  country, function(data){	
       $("#preview").html(data);
        });

});
});
</script>

<% end %>

<%= link_to "Create a New Product", '#', :class => 'addWidget4', :"data-parent-id" => @category2.id, :remote => true %>

<script>
	jQuery(function($) {
	$('.addWidget4').click(function(){
	//($(this).attr('data-parent-id'));
	//$( "#preview" ).html( "<%= escape_javascript( render( :partial => "categories/form.html" ) ) %>" );
	var country = ($(this).attr('data-parent-id'));
    if(country == "") country="0";
     
   $.get('/homes/prodnew/' +  country, function(data){	
       $("#preview").html(data);
        });

});
});
</script>



<!--
<div id="preview"></div> 
-->
</div>
<% end %>
<% end %>
</div>

app/views/homes/_chosencat.html.erb
<b>Category chosen: </b>
<% if !@categoryname.nil? %>
	<%= @categoryname.name %><br />	
<% end %>
<br />

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :main %><br />
    <%= f.text_area :main %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/_product.html.erb
<% if !@product2.nil? %>
<p id="notice"><%= notice %></p>
<div class="leftcolumn3">
<%= image_tag ("/images/b6alum.jpg") %><br />
<%= link_to "View Technical Information", "/almmfti.pdf" %>

</div>
<div class="rightcolumn4">
<div id="choose1">
<% if !@product2.nil? %>
<b>Category: </b>
<% if !@parentcat3.nil? %>
	<%= @parentcat3.name %><br />

<% elsif !@parentcat2.nil? %>
	<%= @parentcat2.name %><br />
	
<% else %>
	<% if !@parentcat.nil? %>
		<%= @parentcat.name %>
	<% end %>
<% end %>	
<% end %>
</div>
<div id="choose2">
<% if !@product2.nil? %>

<% if !@parentcat3.nil? %>
	
	<% if !@parentcat2.nil? %>
	<b>Sub Category: </b>
		<%= @parentcat2.name %><br />
	<% end %>	
<% else %>
	<% if !@parentcat2.nil? %>
	<% if !@parentcat.nil? %>
	<b>Sub Category: </b>
		<%= @parentcat.name %>
	<% end %>
	<% end %>
<% end %>	
<% end %>

</div>




<% if !@product2.nil? %>
<% if @parentcat3.nil?  || @parentcat2.nil? %>


<% else %>
<% if !@parentcat.nil? %>
<b>Sub sub Category:</b>
	<%= @parentcat.name %>
<% end %>	
<% end %>
<% end %>

<br />
<b>Product type:</b>
<% if !@product2.nil? %>
<%= @product2.name %>
<% end %>
<br /><%= link_to "Upload an image for this product", "#" %> <br />
  <%= link_to "Upload a document for this product", "#" %>
</div>

<div class="list" >
<!--
<p>
  <b>Parentid:</b>
  <%= @product2.parentid %>
</p>
-->
<p>
  <b>Product Variation Name:</b>
  <%= @product2.name %>
</p>
<p>
<b>Part No.:</b>
<%=@product2.partno %>
</p>


<p>
<b>Type:</b>
<%=@product2.prodtype %>
</p>
<p>
<b>Style:</b>
<%=@product2.style %>
</p>
<p>
<b>Inlet:</b>
<%=@product2.inlet %>
</p>
<p>
<b>Hose:</b>
<%=@product2.hose %>
</p>
<p>
<b>Plug:</b>
<%=@product2.plug %>
</p>
<p>
<b>Weight:</b>
<%=@product2.weight %>
</p>
<p>
<b>Qty.:</b>
<%=@product2.quanity %>
</p>


<p>
  <b>Model:</b>
  <%= @product2.model %>
</p>

<p>
  <b>Port size:</b>
  <%= @product2.ports %>
</p>
<p>
<b>No. of Ports:</b>
<%=@product2.portno %>
</p>


<p>
  <b>Valve:</b>
  <%= @product2.valve %>
</p>

<p>
  <b>Color:</b>
  <%= @product2.color %>
</p>

<p>
  <b>Price:</b>
  <%= @product2.price %>
</p>
<p>
  <b>Flow Rate GPM/LPM:</b>
  <%= @product2.flow %>
</p>
<p>
  <b>Thread Size:</b>
  <%= @product2.thread %>
</p>
<% if @product2.custom1check == 1 %>
<p>
  <b><%= @product2.custom1name %>:</b>
  <%= @product2.custom1 %>
</p>
<% end %>

<!--
<p>
  <b>Category:</b>
  <%= @product2.category_id %>
</p>
-->

<% if !@product2.nil? %>
<% if !@product2.parentid.nil? %>

<%= link_to "Copy this Product Variation", '#', :class => 'copy2', :"data-product-id" => @product2.id, :remote => true %>
<% else %>
<% @productname = @product2 %>
<%= link_to "Create a Product Variation", '#', :class => 'copy3', :"data-product-id" => @product2.id, :remote => true %>
<% end %>
<script>
jQuery(function($) {

	$('.copy2').click(function() {
   //$(this).css("backgroundColor", "blue");
   ($(this).attr('data-product-id'));
   
   var country = ($(this).attr('data-product-id'));
    if(country == "") country="0";
   
   jQuery.get('/homes/copy/' +  country, function(data){
        $("#results").html(data);   
      })
    return false;
 });
 });  
</script>

<script>
	jQuery(function($) {
	$('.copy3').click(function(){
	($(this).attr('data-product-id'));
	var parent = ($(this).attr('data-product-id'));
	jQuery.get('/homes/variation/' +  parent, function(data){
        $("#results").html(data);   
      });
	//$( "#results" ).html( "<%= escape_javascript( render( :partial => "products/form.html" ) ) %>" );
});
});
</script>

<% end %>
</div>
<% end %>

app/views/homes/_searchresults.html.erb
<div class="list2">
<div id="choose1">
<% if !@categoryname.nil? %>
<b>Category chosen: </b>
	<span class="list3"><%= @categoryname.name %></span><br />	
<% end %>
</div>
<div id="choose2">
<% if !@categoryname2.nil? %>
<b>Sub Category chosen: </b>
	<span class="list3"><%= @categoryname2.name %></span><br />	
<% end %>
</div>
</div>
<br />



<% if !@categoryname.nil? %>


<%= link_to "Create a New Sub Category", '#', :class => 'addWidget2', :"data-parent-id" => @categoryname.id, :remote => true %>

<% else %>
<%= link_to "Create a New Sub Category", '#', :class => 'addWidget2', :remote => true %>
<% end %>
<script>
	jQuery(function($) {
	$('.addWidget2').click(function(){
	($(this).attr('data-parent-id'));
	$( "#preview" ).html( "<%= escape_javascript( render( :partial => "categories/form.html" )) %>" );
	


});
});
</script>

<div id="preview"></div>

<% if !@categoryname.nil? %>	


	<% @subcatlist=[] %>
	<% @categories.each do |category| %>
		<% if category.parentid == @categoryname.id %>
			<% @subcatlist << category %>
		<% end %>
	<% end %>

	<% if !@subcatlist.empty? %> <!-- Then there is a sub category -->
	
	
<br />


or 

<br />

		
		
	<br /><b>Choose a sub category:</b>
	<%= select_tag 'subcat', options_from_collection_for_select(@subcatlist, 'id', 'name'), :include_blank => 'None', :remote => true %>
<br />
<script>
jQuery(function($) {
	$('#subcat').change(function() {
   //$(this).css("backgroundColor", "blue");
   
   var country = $('select#subcat :selected').val();
    if(country == "") country="0";
   
   	$.get('/homes/search3/' +  country, function(data){
        $("#results").html(data);   
      });
   // return false;
     $.get('/homes/choose2/' +  country, function(data){	
        $("#preview").html(data);   
         });
 });
 });  
</script>
<div id='results'></div>	
		
		
		
		
	<% end %>
<% end %>


<% if !@categoryname2.nil? %>
This is getting refreshed
<%= @categoryname2.name %>
<% end %>

<% if !@categoryname.nil? && @categoryname2.nil? %>

<br />
or
<br />

<%= link_to "Create a New Product", '#', :class => 'addWidget4', :"data-cat-id" => @categoryname.id, :include_blank => 'None', :remote => true %>
<% end %>
<script>
	jQuery(function($) {
	$('.addWidget4').click(function(){
	($(this).attr('data-cat-id'));
	$( "#preview" ).html( "<%= escape_javascript( render( :partial => "products/form.html" ) ) %>" );
});
});
</script>

<div id="preview"></div>




<% if !@categoryname.nil? %>
<br />
or
<br />
<b> Choose a product</b>


<%= select_tag 'product2', options_from_collection_for_select(@products, 'id', 'name'), :include_blank => 'None', :remote => true %>

<br />
<script>
jQuery(function($) {
	$('#product2').click(function() {
   //$(this).css("backgroundColor", "blue");
   
   var country = $('select#product2 :selected').val();
    if(country == "") country="0";
   
   jQuery.get('/homes/search2/' +  country, function(data){
        $("#results").html(data);   
      });
    $.get('/homes/choose4/' +  country, function(data){
        $("#preview").html(data);   
      });
 });
 });  


</script>
<div id="results"></div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Listing homes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Main</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homes.each do |home| %>
  <tr>
    <td><%= home.name %></td>
    <td><%= home.main %></td>
    <td><%= link_to 'Show', home %></td>
    <td><%= link_to 'Edit', edit_home_path(home) %></td>
    <td><%= link_to 'Destroy', home, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="leftcolumn">
<!--
<p>
  <b>Name:</b>
  <%= @home.name %>
</p>

<p>
  <b>Main:</b>
  <%= @home.main %>
</p>

<p>
<%= @home.main %><br />

</p>
<p>
<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>
</p>
-->
<!-- <div id = 'results'></div>-->
<div id = 'preview'>
<% if @product2.nil? && @category2.nil? %>


Welcome to the administrator pages of the Plastixs website. Please create or select a category to get started.
<% end %>

<% if !@category2.nil? %>
<div class="" >

<%= render(:partial => 'category.html') %>

</div>
<% end %>
<% if @category2.nil? %>
<div class="" >
<%= render(:partial => 'product.html') %>
</div>
<% end %>
</div>
<div id="choose1">
<% if !@categoryname.nil? %>
	<%= @categoryname.name %><br />	
<% end %>
</div>



</div>
<div class="rightcolumn">

<%= link_to "Create a New Main Category", '#', :class => 'addWidget',:id =>'parent', :"data-parent-id" => '156', :remote => true %>
<%= params[:addWidget] %>
<script>
	jQuery(function($) {
	$('.addWidget').click(function(){
	var parent = $('#parent').attr('data-parent-id');
	
	//$("#parent").attr("data-parent-id", function (arr) {
 	//return "parent-data-parent-id" + arr;
	//})

	$("#preview" ).html( "<%= escape_javascript( render( :partial => "categories/initform.html")) %>" );
});
});
</script>

<div id="preview">

</div>

<br />
<b>Choose a category:</b>
<%= select_tag 'category2', options_from_collection_for_select(@categoryinit, 'id', 'name'), :include_blank => 'None', :remote => true %>
<br />
<script>
jQuery(function($) {
	$('#category2').change(function() {
   //$(this).css("backgroundColor", "blue");
   	var country = $('select#category2 :selected').val();
    if(country == "") country="0";
     
   $.get('/homes/search/' +  country, function(data){	
       $("#results").html(data);
        });
        $.get('/homes/choose/' +  country, function(data){	
        $("#preview").html(data);   
         });
        //$("#preview" ).html( "<%= escape_javascript( render( :partial => "category.html")) %>" );
 
        //jQuery.get("/homes/choose/" + country, function(data){
    //$("#preview").html(data);
     
      
    //return false;
    
   
 });
 
 });  
 //$("#choose1" ).html(data);
  
</script>
<div id='results'></div>
<div id='choose1'></div>





</div>